version: '3.8'
name: grid
services:
  mysql:
    image: mysql
    container_name: grid-mysql
    ports:
      - "3307:3306"
    env_file:
      - src/main/resources/db/db.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grid-phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - src/main/resources/db/db.env
  grid:
    image: backend
    container_name: grid-backend
    build:
      context: ../../..
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - keycloak
      - keycloak-db
    env_file:
      - src/main/resources/db/db.env
    volumes:
      - ./target:/app/target

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    env_file: src/main/resources/keycloak/config/keycloak.env

    ports:
      - "8084:8080"
    depends_on:
      - keycloak-db
    command:
      - start-dev
  keycloak-db:
    container_name: keycloak-db
    image: postgres:latest
    env_file:
      - src/main/resources/keycloak/config/keycloak.env

networks:
  grid:
    external: true
    name: none