version: '3.8'
name: grid
services:
  mysql:
    image: mysql
    container_name: grid-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: GridDB
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grid-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: spring
  grid:
    image: backend
    container_name: grid-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=spring
      - DB_PASSWORD=spring
      - DB_URL=jdbc:mysql://grid-mysql:3306/GridDB?allowPublicKeyRetrieval=true&useSSL=false
    volumes:
      - ./target:/app/target
networks:
  grid:
    external: true
    name: none