version: '1.0'
name: grid
services:
  mysql:
    image: mysql
    container_name: grid-mysql
    ports:
      - "3307:3306"
    env_file:
      - src/main/resources/db/db.env
    volumes:
      - ./src/main/resources/db/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grid-phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - src/main/resources/db/db.env
  grid:
    image: backend
    container_name: grid-backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - keycloak
    env_file:
      - src/main/resources/db/db.env
    volumes:
      - ./target:/app/target
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    env_file:
      - src/main/resources/imports/keycloak.env
    build:
      context: ../../..
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - keycloakdb
    command: -v start-dev --import-realm --features=account3,declarative-user-profile
    volumes:
      - ./src/main/resources/imports:/opt/keycloak/data/import/
      - ./src/main/resources/imports:/opt/keycloak/providers/
  keycloakdb:
    container_name: keycloakdb
    image: postgres:latest
    env_file:
      - src/main/resources/imports/keycloak.env
networks:
  grid:
    external: true
    name: grid