server:
  port: 8082
  max-http-request-header-size: 10000
app:
  front-url: http://localhost:3000
  payment:
    unitAmount: "100"
    currencyApi: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?valcode=EUR
    paypal:
      base-api-url: https://api-m.sandbox.paypal.com
      paypal-id: ${PAYPAL_CLIENT_ID}
      paypal-secret: ${PAYPAL_SECRET_KEY}
      currency_EURO: "EUR"
    stripe:
      currency: "uah"
      stripe-secret: ${STRIPE_SECRET_KEY}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/GRID
  jpa:
    generate-ddl: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    enabled: 'true'
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
#logging:
#  level:
#    root: trace
logging:
  level:
    org:
      springframework:
        security: trace