server:
  port: 8082
  max-http-request-header-size: 15000
app:
  googleai:
    api:
      prompt-template: ${GOOGLE_API_TEXT_PROMPT}
      model: ${GOOGLE_API_MODEL}
      projectId: ${GOOGLE_API_PROJECT_ID}
      location: ${GOOGLE_API_LOCATION}
  front-url: http://localhost:3000
  payment:
    unitAmount: "100"
    currencyApi: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?valcode=EUR
    paypal:
      base-api-url: https://api-m.sandbox.paypal.com
      paypal-id: ${PAYPAL_CLIENT_ID}
      paypal-secret: ${PAYPAL_SECRET_KEY}
      currency_EURO: "EUR"
    stripe:
      currency: "uah"
      stripe-secret: ${STRIPE_SECRET_KEY}
jwt:
  auth:
    converter:
      resource-id: login-app
      principal-attribute: preferred_username
spring:
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.grid.domain-for-tests.com/realms/GRID
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: 'false'
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  flyway:
    enabled: 'false'
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
logging:
  level:
    #    org.springframework: trace
    org.springframework.security: trace