server:
  port: 8082
spring:
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: 'false'
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: 'false'
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
jwt:
  jwt-secret: ======================GRID=Spring===========================
  jwt-cookie-name: grid-jwt
  jwt-cookie-path: /api
  jwt-expiration-Ms: 60000
  jwt-cookie-max-age: 60
