server:
  port: 8082
  max-http-request-header-size: 10000
app:
  cors:
    allowed-origins: http://localhost:3000
jwt:
  auth:
    converter:
      resource-id: login-app
      principal-attribute: preferred_username
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/GRID
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: 'false'
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  flyway:
    enabled: 'false'
springdoc:
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
logging:
  level:
    org.springframework.security: trace