server:
  port: 8082
spring:
  jpa:
    generate-ddl: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    enabled: 'true'
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 468326435487-k6mu6lh29tik37qthnl3eo6rb9u1nlss.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
jwt:
  jwt-secret: ======================GRID=Spring===========================
  jwt-cookie-name: grid-jwt
  jwt-cookie-path: /api
  jwt-expiration-Ms: 86400000
  jwt-cookie-max-age: 86400