version: '1.0'
name: grid
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    env_file:
    - imports/keycloak.env

    ports:
      - "8084:8080"
    depends_on:
      - keycloak-db
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import/
  keycloak-db:
    container_name: keycloak-db
    image: postgres:latest
    env_file:
      - imports/keycloak.env
networks:
  grid:
    external: true
    name: none