server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8084/realms/GRID
        registration:
          keycloak:
            client-name: Login-App
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid,profile,email,offline_access
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: 'false'
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: 'false'
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger