name: Java CI

on:
  workflow_dispatch: 
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        java-version: [17.x]
        
    steps:
      - uses: actions/checkout@v1
      - name: Check docker containers 
        run: docker ps
      - name: Delete .env default files 
        run: cd ./src/main/resources && rm -rf application-docker.yml && rm -rf keys.env 
      - name: Сopy .env default files 
        run:  cd ../../../ && cp application-docker.yml ./_work/backend/backend/src/main/resources && cp keys.env ./_work/backend/backend/src/main/resources
      - name: Сopy .env default files 
        run: cd ./src/main/resources && ls
      - name: Stop all docker containers 
        continue-on-error: true
        run: docker stop $(docker ps -q) 
      - name: Remove backend and DB containers  
        continue-on-error: true
        run: docker rm grid-backend && docker rm grid-mysql && docker rmi -f $(docker images -aq) 
      - name: Docker compose up
        run: docker compose up -d 
      - name: Set auto start
        continue-on-error: true
        run: docker update --restart unless-stopped $(docker ps -q)
      - name: Kill java process 
        continue-on-error: true
        run: sudo pkill -f 'java -jar' 
      - run: export SPRING_PROFILES_ACTIVE=docker
      - run: ls ; mvn clean package
      - name: Rename the artifact
        run: ls; cp target/grid-0.0.1-SNAPSHOT.jar grid-0.0.1-SNAPSHOT.jar
      - run: sudo nohup java -jar -Dspring.profiles.active=docker grid-0.0.1-SNAPSHOT.jar 


                  
